// @ts-nocheck -- skip type checking
import * as docs_7 from "../app/docs/computer-science/data-structures/linked-list/index.mdx?collection=docs&hash=1757698225160"
import * as docs_6 from "../app/docs/computer-science/data-structures/linked-list/01-singly-linked-list.mdx?collection=docs&hash=1757698225160"
import * as docs_5 from "../app/docs/computer-science/data-structures/array/index.mdx?collection=docs&hash=1757698225160"
import * as docs_4 from "../app/docs/computer-science/data-structures/array/02-dynamic-array.mdx?collection=docs&hash=1757698225160"
import * as docs_3 from "../app/docs/computer-science/data-structures/array/01-static-array.mdx?collection=docs&hash=1757698225160"
import * as docs_2 from "../app/docs/computer-science/data-structures/index.mdx?collection=docs&hash=1757698225160"
import * as docs_1 from "../app/docs/guide/HelloWorld.md?collection=docs&hash=1757698225160"
import * as docs_0 from "../app/docs/computer-science/index.mdx?collection=docs&hash=1757698225160"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"computer-science\\index.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/index.mdx"}, data: docs_0 }, { info: {"path":"guide\\HelloWorld.md","absolutePath":"D:/work/involutionhell.github.io/app/docs/guide/HelloWorld.md"}, data: docs_1 }, { info: {"path":"computer-science\\data-structures\\index.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/index.mdx"}, data: docs_2 }, { info: {"path":"computer-science\\data-structures\\array\\01-static-array.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/array/01-static-array.mdx"}, data: docs_3 }, { info: {"path":"computer-science\\data-structures\\array\\02-dynamic-array.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/array/02-dynamic-array.mdx"}, data: docs_4 }, { info: {"path":"computer-science\\data-structures\\array\\index.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/array/index.mdx"}, data: docs_5 }, { info: {"path":"computer-science\\data-structures\\linked-list\\01-singly-linked-list.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/linked-list/01-singly-linked-list.mdx"}, data: docs_6 }, { info: {"path":"computer-science\\data-structures\\linked-list\\index.mdx","absolutePath":"D:/work/involutionhell.github.io/app/docs/computer-science/data-structures/linked-list/index.mdx"}, data: docs_7 }], [])